spring.application.name=PiraProject

# Database Connection Configuration
spring.datasource.url=jdbc:postgresql://aws-1-eu-central-1.pooler.supabase.com:5432/postgres?sslmode=require&prepareThreshold=0
spring.datasource.username=postgres.ztuvnseblcmmaryodzyl
spring.datasource.password=Pp59867920@
spring.datasource.driver-class-name=org.postgresql.Driver

# Hibernate settings to automatically create tables for us
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect